---
- name: Deploy Docker Container
  hosts: localhost
  connection: local
  tasks:
  - name: Build Docker image
    docker_image:
      name: sample-web-app
      source: build
      build:
        path: .
      state: present

  - name: Run Docker container
    docker_container:
      name: sample-web-app-container
      image: sample-web-app
      state: started
      ports:
      - "5000:5000"
